name: Deploy mdBook site to Pages

on:
  # Run on all branches
  push:
    branches:
      - "*"
  # Allow running manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow only one concurrent deployment, but don't cancel existing one
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Restore Cargo cache
        id: cache-cargo
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo

      - name: Setup cacheable Cargo extensions
        run: |
          cargo install mdbook-admonish mdbook-footnote mdbook-graphviz mdbook-mermaid
        if: steps.cache-cargo.outputs.cache-hit != 'true'

      - name: Store Cargo cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ steps.cache-cargo.outputs.cache-primary-key }}
        if: steps.cache-cargo.outputs.cache-hit != 'true'

      - name: Restore static cache
        id: cache-static
        uses: actions/cache/restore@v3
        with:
          path: |
            ./devicon.*
            ./src/fonts/devicon.*
            ./src/assets/whichlang.*
          key: ${{ runner.os }}-static

      - name: Setup cacheable static extensions
        run: |
          mkdir -p src/fonts
          curl -sSf -o devicon.min.css https://raw.githubusercontent.com/devicons/devicon/master/devicon.min.css
          curl -sSf -o src/fonts/devicon.eot https://raw.githubusercontent.com/devicons/devicon/master/fonts/devicon.eot
          curl -sSf -o src/fonts/devicon.svg https://raw.githubusercontent.com/devicons/devicon/master/fonts/devicon.svg
          curl -sSf -o src/fonts/devicon.ttf https://raw.githubusercontent.com/devicons/devicon/master/fonts/devicon.ttf
          curl -sSf -o src/fonts/devicon.woff https://raw.githubusercontent.com/devicons/devicon/master/fonts/devicon.woff
          curl -sSf -o src/assets/whichlang.css https://raw.githubusercontent.com/phoenixr-codes/mdbook-whichlang/master/src/whichlang.css
          curl -sSf -o src/assets/whichlang.js https://raw.githubusercontent.com/phoenixr-codes/mdbook-whichlang/master/dist/whichlang.js
        if: steps.cache-static.outputs.cache-hit != 'true'

      - name: Store static cache
        uses: actions/cache/save@v3
        with:
          path: |
            ./devicon.*
            ./src/fonts/devicon.*
            ./src/assets/whichlang.*
          key: ${{ steps.cache-static.outputs.cache-primary-key }}
        if: steps.cache-static.outputs.cache-hit != 'true'

      - name: Setup non-cacheable extensions
        run: |
          sudo apt update && sudo apt install -y graphviz
          mdbook-admonish install --css-dir src/assets .
          mdbook-mermaid install .
      - name: Build with mdBook
        run: mdbook build

      - name: Turn off Jekyll
        run: touch book/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
